# Generated by Django 2.2.1 on 2019-05-21 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rental_status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Rented Out')], default=0),
        ),
        migrations.AlterField(
            model_name='rental',
            name='date_borrowed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Closed')], default=0),
        ),
    ]
