# Generated by Django 2.2.1 on 2019-05-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rental_amount_charged'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('R', 'Regular'), ('F', 'Fiction'), ('N', 'Novel')], default='R', max_length=2),
        ),
    ]
